Repository boostcampwm-2021/web10-CowDogTing, pull requests merged in 2021-11, with the labels that each got.

#28 [ jin-Pro ] LoginPage / RegisterPage / Button.tsx / Input.tsx
  client/package-lock.json
  client/src/App.tsx
  client/src/Atom/Button.tsx
  client/src/Atom/Input.tsx
  client/src/Page/LogInPage.tsx
  client/src/Page/RegisterPage.tsx
  client/src/Page/index.tsx
  client/src/util/reset.tsx
  client/src/util/type.tsx
  client/yarn.lock
Labels: :crown: 리뷰 요청

#33 [ddaynew365] 백엔드 개발 환경 세팅[#10]
  client/package-lock.json
  client/yarn.lock
  server/.eslintrc.json
  server/.prettierrc.json
  server/src/api/index.ts
  server/src/app.ts
  server/src/controllers/index.ts
  server/src/www.ts
  server/tsconfig.json
Labels: BE

#57 [Feat/my page] Mypage UI
  client/package-lock.json
  client/src/App.tsx
  client/src/Atom/Menu.tsx
  client/src/Atom/SideBarDiv.tsx
  client/src/Atom/UserIcon.tsx
  client/src/Molecules/DropDown.tsx
  client/src/Molecules/MainHeaderCenter.tsx
  client/src/Molecules/MainHeaderRightSide.tsx
  client/src/Organism/Header.tsx
  client/src/Organism/MainHeader.tsx
  client/src/Organism/MyInfoContainer.tsx
  client/src/Organism/MyPageSideBar.tsx
  client/src/Page/MyPage.tsx
  client/src/Template/MyPageBodyTemplate.tsx
  client/src/Template/MyPageMain/LikeList.tsx
  client/src/Template/MyPageMain/MyInfo.tsx
  client/src/Template/MyPageMain/QuestionList.tsx
  client/src/Template/MyPageMain/Review.tsx
  client/src/Template/MyPageTemplate.tsx
  client/src/assets/Menu.png
Labels: FE

#60 [팀 설정 페이지] 팀 멤버 프로필 UI
  client/src/App.tsx
  client/src/Molecules/MainBodyLeftButtonContainer.tsx
  client/src/Organism/TeamInfoContainer.tsx
  client/src/Organism/TeamSettingMemberContainer.tsx
  client/src/Page/Page.tsx
  client/src/Page/TeamCreatePage.tsx
  client/src/Page/TeamSettingPage.tsx
  client/src/Template/TeamSettingTemplate.tsx
  client/src/util/type.tsx
Labels: :crown: 리뷰 요청, FE

#78 [ 팀 설정 페이지 ] 이미지 업로드 구현
  client/src/Atom/ProfileImage.tsx
  client/src/Organism/TeamInfoContainer.tsx
  client/src/Organism/TeamInfoImageContainer.tsx
  client/src/util/type.tsx
Labels: :crown: 리뷰 요청, FE

#73 [ddaynew365] 데이터베이스 초안 모델 생성
  server/config/config.ts
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/migrations/createTableAll.ts
  server/src/migrations/tables/1.users.ts
  server/src/migrations/tables/2.team.ts
  server/src/migrations/tables/3.chat.ts
  server/src/migrations/tables/4.request.ts
  server/src/migrations/tables/5.sendRequest.ts
  server/src/migrations/tables/6.chatRoom.ts
  server/src/migrations/tables/7.enterRoom.ts
  server/src/models/chat.ts
  server/src/models/chatRoom.ts
  server/src/models/enterRoom.ts
  server/src/models/index.ts
  server/src/models/request.ts
  server/src/models/sendRequest.ts
  server/src/models/team.ts
  server/src/models/users.ts
  server/src/www.ts
Labels: BE

#82 [ ddaynew365 ] 요청 페이지 레이아웃 구현 및 더미 데이터 연동
  .vscode/launch.json
  client/src/Page/Page.tsx
  client/src/Page/RequestPage.tsx
Labels: FE

#83 [ 채팅 목록 페이지 ] 채팅 목록 페이지 UI 구현
  client/src/Atom/ProfileCard.tsx
  client/src/Atom/ProfileImage.tsx
  client/src/Molecules/ChatInput.tsx
  client/src/Molecules/ChatProfileInfoContainer.tsx
  client/src/Molecules/ProfileImageContainer.tsx
  client/src/Organism/ChatDetail.tsx
  client/src/Organism/ChatImageContainer.tsx
  client/src/Organism/ChatInputContainer.tsx
  client/src/Organism/ChatListContainer.tsx
  client/src/Organism/ChatProfileContainer.tsx
  client/src/Organism/TeamInfoImageContainer.tsx
  client/src/Page/ChatListPage.tsx
  client/src/Page/ChatRoom.tsx
  client/src/Page/Page.tsx
  client/src/Template/ChatListTemplate.tsx
  client/src/util/dummyData.tsx
  client/src/util/type.tsx
Labels: :crown: 리뷰 요청, FE

#84 Feat/chat room page
  client/public/character/캐릭터1.png
  client/public/character/캐릭터2.png
  client/public/character/캐릭터3.png
  client/public/character/캐릭터4.png
  client/public/character/캐릭터5.png
  client/src/Atom/Button.tsx
  client/src/Atom/Video.tsx
  client/src/Molecules/ChatRoomBasic.tsx
  client/src/Molecules/ChatRoomFooter.tsx
  client/src/Molecules/ChatRoomGame.tsx
  client/src/Molecules/VideoSupport.tsx
  client/src/Page/ChatRoom.tsx
  client/src/Template/ChatRoomGather.tsx
  client/src/Template/ChatRoomRight.tsx
  client/src/util/dummyData.tsx
  client/src/util/type.tsx
Labels: :crown: 리뷰 요청

#114 [ ddaynew365 ] swagger 및 passport 로그인 구현
  server/package-lock.json
  server/package.json
  server/src/api/index.ts
  server/src/api/passport/index.ts
  server/src/api/passport/localStrategy.ts
  server/src/api/routes/auth/auth.ts
  server/src/api/routes/middlewares/isAuth.ts
  server/src/app.ts
  server/src/migrations/tables/1.team.ts
  server/src/migrations/tables/1.users.ts
  server/src/migrations/tables/2.team.ts
  server/src/migrations/tables/2.users.ts
  server/src/models/chatRoom.ts
  server/src/models/enterRoom.ts
  server/src/models/request.ts
  server/src/models/sendRequest.ts
  server/src/models/team.ts
  server/src/models/users.ts
  server/src/public/docs/favicon-16x16.png
  server/src/public/docs/favicon-32x32.png
  server/src/public/docs/index.html
  server/src/public/docs/oauth2-redirect.html
  server/src/public/docs/swagger-ui-bundle.js
  server/src/public/docs/swagger-ui-es-bundle-core.js
  server/src/public/docs/swagger-ui-es-bundle-core.js.map
  server/src/public/docs/swagger-ui-es-bundle.js
  server/src/public/docs/swagger-ui-standalone-preset.js
  server/src/public/docs/swagger-ui-standalone-preset.js.map
  server/src/public/docs/swagger-ui.css
  server/src/public/docs/swagger-ui.css.map
  server/src/public/docs/swagger-ui.js
  server/src/public/docs/swagger-ui.js.map
  server/src/public/swagger.yaml
  server/src/www.ts
Labels: BE

#120 [ Team 관련 API ] 팀 관련 API 구현
  client/package-lock.json
  client/package.json
  client/src/Molecules/InputLabel.tsx
  client/src/Page/LogInPage.tsx
  client/src/Page/RegisterPage.tsx
  client/src/Page/TeamCreatePage.tsx
  client/src/Template/InviteModal.tsx
  client/src/Template/TeamSettingTemplate.tsx
  client/src/util/dummyData.ts
  client/src/util/type.ts
  client/yarn.lock
  server/.eslintrc.json
  server/package-lock.json
  server/package.json
  server/src/api/auth/controller.ts
  server/src/api/auth/index.ts
  server/src/api/auth/service.ts
  server/src/api/chat/controller.ts
  server/src/api/chat/index.ts
  server/src/api/chat/service.ts
  server/src/api/core/controller.ts
  server/src/api/core/index.ts
  server/src/api/core/service.ts
  server/src/api/index.ts
  server/src/api/middlewares/isAuth.ts
  server/src/api/routes/auth/auth.ts
  server/src/api/team/controller.ts
  server/src/api/team/index.ts
  server/src/api/team/service.ts
  server/src/app.ts
  server/src/controllers/index.ts
  server/src/migrations/tables/1.team.ts
  server/src/migrations/tables/3.chat.ts
  server/src/migrations/tables/3.request.ts
  server/src/migrations/tables/4.chatRoom.ts
  server/src/migrations/tables/4.request.ts
  server/src/migrations/tables/5.participant.ts
  server/src/migrations/tables/5.sendRequest.ts
  server/src/migrations/tables/6.chat.ts
  server/src/migrations/tables/6.chatRoom.ts
  server/src/migrations/tables/7.enterRoom.ts
  server/src/migrations/tables/7.image.ts
  server/src/models/chat.ts
  server/src/models/chatRoom.ts
  server/src/models/enterRoom.ts
  server/src/models/image.ts
  server/src/models/participant.ts
  server/src/models/request.ts
  server/src/models/team.ts
  server/src/models/users.ts
  server/src/passport/index.ts
  server/src/passport/localStrategy.ts
  server/src/public/swagger.yaml
Labels: :crown: 리뷰 요청, FE, BE

#121 [ ddaynew365 ] 코어 API 구현
  server/package.json
  server/src/api/auth/service.ts
  server/src/api/chat/service.ts
  server/src/api/core/controller.ts
  server/src/api/core/index.ts
  server/src/api/core/service.ts
  server/src/api/team/service.ts
  server/src/db/migrations/createTableAll.ts
  server/src/db/migrations/tables/1.team.ts
  server/src/db/migrations/tables/2.users.ts
  server/src/db/migrations/tables/3.request.ts
  server/src/db/migrations/tables/4.chatRoom.ts
  server/src/db/migrations/tables/5.participant.ts
  server/src/db/migrations/tables/6.chat.ts
  server/src/db/migrations/tables/7.image.ts
  server/src/db/models/chat.ts
  server/src/db/models/chatRoom.ts
  server/src/db/models/image.ts
  server/src/db/models/index.ts
  server/src/db/models/participant.ts
  server/src/db/models/request.ts
  server/src/db/models/team.ts
  server/src/db/models/users.ts
  server/src/db/seeders/createDataAll.ts
  server/src/db/seeders/seed/20211110013049-team.ts
  server/src/db/seeders/seed/20211110013052-user.ts
  server/src/db/seeders/seed/20211110013057-request.ts
  server/src/db/seeders/seed/20211110013120-chatRoom.ts
  server/src/db/seeders/seed/20211110013127-participant.ts
  server/src/db/seeders/seed/20211110013128-chat.ts
  server/src/migrations/tables/2.users.ts
  server/src/models/index.ts
  server/src/passport/index.ts
  server/src/passport/localStrategy.ts
  server/src/public/swagger.yaml
  server/src/www.ts
Labels: BE

#133 [ J039 ] : FE => Profile Modal Close Event
  client/src/Hook/useModalEvent.tsx
  client/src/Molecules/ChatRoomFooter.tsx
  client/src/Organism/ChatImageContainer.tsx
  client/src/Organism/ChatListContainer.tsx
  client/src/Organism/ChatProfileContainer.tsx
  client/src/Page/CowDogPage.tsx
  client/src/Page/RequestPage.tsx
  client/src/Template/ChatListTemplate.tsx
  client/src/Template/ProfileList.tsx
  client/src/Template/TeamSettingTemplate.tsx
  client/src/util/type.ts
Labels: :crown: 리뷰 요청

#137 [Feat/requestlist] Pair-Programming
  client/src/App.tsx
  client/src/Atom/Button.tsx
  client/src/Atom/TeamCreateIcon.tsx
  client/src/Molecules/DropDown.tsx
  client/src/Molecules/MainBodyLeftButtonContainer.tsx
  client/src/Molecules/MainHeaderCenter.tsx
  client/src/Molecules/MainHeaderRightSide.tsx
  client/src/Organism/Header.tsx
  client/src/Organism/MainHeader.tsx
  client/src/Organism/MyInfoContainer.tsx
  client/src/Page/CowDogPage.tsx
  client/src/Page/LogInPage.tsx
  client/src/Page/Page.tsx
  client/src/Page/RegisterPage.tsx
  client/src/Page/RequestPage.tsx
  client/src/Page/TeamCreatePage.tsx
  client/src/Page/TeamSettingPage.tsx
  client/src/Recoil/Atom.tsx
  client/src/Recoil/Selector.tsx
  client/src/Template/InviteModal.tsx
  client/src/Template/RequestList.tsx
  client/src/Template/TeamSettingTemplate.tsx
  client/src/index.tsx
  client/src/util/constant.ts
  client/src/util/dummyData.ts
  client/src/util/index.ts
  client/src/util/type.ts
  client/src/util/utilFunc.ts
  server/package-lock.json
  server/package.json
  server/src/api/auth/controller.ts
  server/src/api/chat/service.ts
  server/src/api/core/controller.ts
  server/src/api/core/index.ts
  server/src/api/core/service.ts
  server/src/api/team/service.ts
  server/src/app.ts
  server/src/db/models/image.ts
  server/src/passport/index.ts
Labels: :crown: 리뷰 요청, FE

#141 [ FE & BE ] core API 수정 & 연동
  client/src/App.tsx
  server/src/api/core/controller.ts
Labels: FE, BE

#153 [ FE ] Feat/recoil refactor
  client/src/App.tsx
  client/src/Atom/Chat.tsx
  client/src/Atom/RequestButton.tsx
  client/src/Molecules/ChatRoomFooter.tsx
  client/src/Organism/ChatDetail.tsx
  client/src/Organism/LargeModal.tsx
  client/src/Page/CowDogPage.tsx
  client/src/Page/RequestPage.tsx
  client/src/Recoil/Atom.tsx
  client/src/Template/ChatListTemplate.tsx
  client/src/Template/ChatRoomRight.tsx
  client/src/Template/ProfileModal.tsx
  client/src/Template/RequestList.tsx
  client/src/Template/RequestModal.tsx
  client/src/util/constant.ts
  client/src/util/dummyData.ts
  client/src/util/type.ts
Labels: FE

#157 [ FE/BE ] 리코일 <-> 채팅 리스트 페이지 API 연동
  client/src/Organism/ChatProfileContainer.tsx
  client/src/Template/ChatListTemplate.tsx
  client/src/util/type.ts
  server/src/api/chat/controller.ts
Labels: FE, BE

#158 [Feat/logout] Logout / TeamSetting
  client/src/Molecules/DropDown.tsx
  client/src/Molecules/LinkButton.tsx
  client/src/Molecules/MainHeaderRightSide.tsx
  client/src/Organism/Header.tsx
  client/src/Organism/TeamInfoContainer.tsx
  client/src/Organism/TeamInputContainer.tsx
  client/src/Page/LogInPage.tsx
  client/src/Template/TeamSettingTemplate.tsx
  client/src/util/constant.ts
  client/src/util/index.ts
  client/src/util/type.ts
  server/src/api/auth/controller.ts
Labels: FE

#159 [ ddaynew365 ] 개인정보 수정 API, 팀 전체 프로필 API 오류 수정
  server/.eslintrc.json
  server/src/api/chat/service.ts
  server/src/api/core/controller.ts
  server/src/api/core/index.ts
  server/src/api/core/service.ts
  server/src/db/models/request.ts
  server/src/db/models/team.ts
  server/src/db/models/users.ts
  server/src/public/swagger.yaml
Labels: BE

#185 [ ddaynew365 ] github, kakao 소셜 로그인 연동
  client/src/Page/LogInPage.tsx
  server/package-lock.json
  server/package.json
  server/src/api/auth/controller.ts
  server/src/api/auth/index.ts
  server/src/api/chat/controller.ts
  server/src/api/core/service.ts
  server/src/app.ts
  server/src/passport/githubStrategy.ts
  server/src/passport/index.ts
  server/src/passport/kakaoStrategy.ts
  server/src/public/swagger.yaml
Labels: BE

#186 [Feat/social login] Naver SocialLogin 연동
  client/public/index.html
  client/src/Page/LogInPage.tsx
  package-lock.json
  server/package-lock.json
  server/package.json
  server/src/api/auth/controller.ts
  server/src/api/auth/index.ts
  server/src/passport/index.ts
  server/src/passport/naverStrategy.ts
Labels: :crown: 리뷰 요청, FE

#190 [ BE ] 요청 , 채팅 보내기 API 구현, 소켓 이벤트 구현
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/Socket/index.ts
  server/package-lock.json
  server/package.json
  server/src/api/chat/controller.ts
  server/src/api/chat/service.ts
  server/src/api/core/controller.ts
  server/src/api/core/index.ts
  server/src/api/core/service.ts
  server/src/api/team/service.ts
  server/src/db/models/chat.ts
  server/src/db/models/request.ts
  server/src/db/models/team.ts
  server/src/util/type.ts
  server/src/util/utilFunc.ts
  server/src/webSocket/socket.ts
  server/src/www.ts
Labels: :crown: 리뷰 요청, BE

#197 [Feat/refactor/pages] LoginPage 리팩토링
  client/package-lock.json
  client/src/App.tsx
  client/src/Molecules/LoginButtonContainer.tsx
  client/src/Molecules/LoginMainInput.tsx
  client/src/Molecules/SocialLoginContainer.tsx
  client/src/Page/LogInPage.tsx
  server/package-lock.json
Labels: :crown: 리뷰 요청, FE

#211 [ WebRTC ] 유저 나가기 구현, 음소거 , 비디오끄기 구현
  client/src/Atom/Video.tsx
  client/src/Molecules/ChatRoomBasic.tsx
  server/src/webSocket/socket.ts
  server/src/www.ts
Labels: FE, BE

#232 팀 나가기 기능 / 팀 요청 기능 / 리팩토링 [closes #215 #216 #218 #226 #231]
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/Atom/ProfileInfo.tsx
  client/src/Atom/RequestButton.tsx
  client/src/Molecules/ChatRoomBasic.tsx
  client/src/Molecules/TeamCreateButtonContainer.tsx
  client/src/Molecules/TeamSettingButtonContainer.tsx
  client/src/Page/RequestPage.tsx
  client/src/Template/ProfileModal.tsx
  client/src/Template/RequestList.tsx
  client/src/Template/RequestListContainer.tsx
  client/src/Template/TeamSettingTemplate.tsx
  client/src/util/URL.ts
  client/src/util/data.ts
  client/yarn.lock
  server/src/api/auth/controller.ts
  server/src/api/auth/service.ts
  server/src/api/core/controller.ts
  server/src/api/core/service.ts
  server/src/api/team/controller.ts
  server/src/api/team/index.ts
  server/src/api/team/service.ts
Labels: :crown: 리뷰 요청, FE, BE

#247 [ FE ] css 수정
  client/src/Atom/Input.tsx
  client/src/Container/InfoContainer.tsx
  client/src/Container/TeamButtonContainer.tsx
  client/src/Molecules/Chat/ChatRoomBasic.tsx
  client/src/Molecules/Chat/ChatRoomGame.tsx
Labels: FE

#255 [ FE / BE ] 11/24 작업
  client/src/App.tsx
  client/src/Atom/RequestButton.tsx
  client/src/Container/InfoImageContainer.tsx
  client/src/Organism/Chat/ChatDetail.tsx
  client/src/Organism/Chat/ChatProfileContainer.tsx
  client/src/Socket/chatSocket.ts
  client/src/Template/Modal/InviteModal.tsx
  client/src/Template/TeamSettingTemplate.tsx
  client/yarn.lock
  server/package-lock.json
  server/package.json
  server/src/api/chat/service.ts
  server/src/api/core/controller.ts
  server/src/api/core/service.ts
  server/src/api/team/controller.ts
  server/src/api/team/service.ts
  server/src/webSocket/socket.ts
  server/uploads/blob1637755423628
  server/uploads/ㅁ1637754630143.webp
  server/uploads/ㅁ1637754649992.webp
  server/uploads/ㅁ1637754650682.webp
  server/uploads/ㅁ1637754658357.webp
  server/uploads/ㅁ1637754677655.webp
  server/uploads/ㅁ1637754872838.webp
  server/uploads/ㅁ1637754883097.webp
  server/uploads/ㅁ1637754884721.webp
  server/uploads/스크린샷 2021-11-22 오후 7.45.151637754241496.png
  server/uploads/스크린샷 2021-11-24 오후 7.02.301637755428601.png
  server/uploads/스크린샷 2021-11-24 오후 7.03.061637754258243.png
Labels: FE, BE

#263 redis 적용, 로컬 테스트 완료
  client/src/Molecules/MainPage/MainHeaderRightSide.tsx
  client/src/Organism/Core/Header.tsx
  server/ecosystem.config.js
  server/package-lock.json
  server/package.json
  server/src/loaders/index.ts
Labels: FE, BE

#264 [ BE ] 서버 - Redis 소켓 Map 에 적용
  server/package-lock.json
  server/package.json
  server/src/api/request/service.ts
  server/src/webSocket/socket.ts
Labels: BE

#265 소켓 map - redis 배포서버에 적용
  server/package-lock.json
  server/package.json
  server/src/api/request/service.ts
  server/src/webSocket/socket.ts
Labels: BE

#266 hot fix
  server/src/loaders/index.ts
Labels: BE

#269 [FE] RequestList Style / TeamCreateError 수정
  client/package-lock.json
  client/src/Page/TeamCreatePage.tsx
  client/src/Template/Request/RequestComponent.tsx
  client/src/Template/TeamSettingTemplate.tsx
  server/package-lock.json
Labels: FE

#270 Client/error
  client/package-lock.json
  client/src/Organism/Chat/ChatImageContainer.tsx
  client/src/Organism/MainPage/MainBodyRight.tsx
  client/src/Page/Page.tsx
  client/src/Page/Project.tsx
  client/src/Page/RegisterPage.tsx
  client/src/util/URL.ts
  client/src/util/data.ts
  server/package-lock.json
  server/package.json
  server/src/api/auth/controller.ts
  server/src/api/util.ts
  server/src/webSocket/socket.ts
Labels: FE
